USE [BibliotecaOnline]
GO

/****** Object:  Table [dbo].[BOOK]    Script Date: 11/03/2018 20:34:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BOOK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](250) NULL,
	[RELEASE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


